# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-01 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0024_auto_20191201_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(blank=True, null=True)),
                ('cost', models.CharField(blank=True, max_length=20, null=True)),
                ('message_Id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('status_response', models.CharField(blank=True, choices=[('100', 'Processed'), ('101', 'Sent'), ('102', 'Queued'), ('401', 'RiskHold'), ('402', 'InvalidSenderId'), ('403', 'InvalidPhoneNumber'), ('404', 'UnsupportedNumberType'), ('405', 'InsufficientBalance'), ('406', 'UserInBlacklist'), ('407', 'CouldNotRoute'), ('500', 'InternalServerError'), ('501', 'GatewayError'), ('502', 'RejectedByGateway')], max_length=20, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_message', to='accounts.UserProfile')),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
            },
        ),
    ]
