# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='status',
            field=models.CharField(blank=True, choices=[('started', 'STARTED'), ('in progress', 'IN PROGRESS'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], max_length=20, null=True),
        ),
    ]
