# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-02 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20191202_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'STARTED'), ('1', 'IN PROGRESS'), ('2', 'COMPLETED'), ('-1', 'FAILED')], max_length=50, null=True),
        ),
    ]
