# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-02 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_auto_20191202_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='status',
            field=models.CharField(blank=True, choices=[('ST', 'STARTED'), ('IP', 'IN PROGRESS'), ('CD', 'COMPLETED'), ('FD', 'FAILED')], max_length=50, null=True),
        ),
    ]
